name: ViajanteDoTempo
favicon: null
layout_spectrum: 0.00556
typography_spectrum: 0.57861
title: Viajante Do Tempo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76457798-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.625
  lightness: 0.1438054747413844
  saturation: 0.8832352163735777
  rhythmicContrast: 0.20115109160542488
purpose: []
